Eccomerce/urls.py
from xml.dom.minidom import Document
from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls'))
    ] + urlpatterns

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('detalhe/', views.Detalhe.as_view(), name='detalhe'),
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

]

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProduto.as_view(), name='lista'),
    path('<slug>', views.DetalheProduto.as_view(), name='detalhe'),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(),
         name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(),
         name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),
]

produto/models.py
#from email.mime import image
from hashlib import blake2b
from pickletools import optimize
from re import T
from tabnanny import verbose
from django.db import models
from PIL import Image
import os
from django.conf import settings
# Create your models here.
from django.utils.text import slugify


class Produto(models.Model):
    nome = models.CharField(max_length=255)
    curt_descrition = models.TextField(max_length=255)
    long_descrition = models.TextField()
    imagem = models.ImageField(
        upload_to='product_images/%Y/%m', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    cost_marketing = models.FloatField(verbose_name='Cost')
    cost_marketing_promotion = models.FloatField(
        default=0, verbose_name='Promotion Cost')
    tipo = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variável'),
            ('S', 'Simples'),
        )
    )

    def get_cost_formated(self):
        return f'R$ {self.cost_marketing:.2f}'.replace('.', ',')

    get_cost_formated.short_description = 'Cost'

    def get_cost_promotion_formated(self):
        return f'R$ {self.cost_marketing_promotion:.2f}'.replace('.', ',')

    get_cost_promotion_formated.short_description = 'Promotion Cost'

    @staticmethod
    def resize_image(imagens, new_width=800):
        img_full_path = os.path.join(settings.MEDIA_ROOT, imagens.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            img_pil.close
            return

        new_height = round((new_width * original_height) / original_width)
        print('teste................')
        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)

        new_img.save(img_full_path,
                     optimize=True,
                     quality=50)

    def save(self, *args, **kwargs):

        if not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug

        super().save(*args, **kwargs)

        max_image_size = 800

        if self.imagem:

            self.resize_image(self.imagem, max_image_size)

    def __str__(self):
        return self.nome


class Variacao(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50, blank=True, null=True)
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.nome or self.produto.nome

    class Meta:
        verbose_name = 'Variações'
        verbose_name_plural = 'Variações'

produto/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from . import models
from django.contrib import messages
from utils import utils
from perfil.models import Perfil

# Create your views here.


class ListaProduto(ListView):
    model = models.Produto
    template_name = 'produto/lista.html'
    context_object_name = 'produtos'
    paginate_by = 10


class DetalheProduto(DetailView):
    model = models.Produto
    template_name = 'produto/detalhe.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'


class AdicionarAoCarrinho(View):
    def get(self, *args, **kwargs):
        '''if self.request.session.get('carrinho'):
            del self.request.session['carrinho']
            self.request.session.save()'''
        http_referer = self.request.META.get('HTTP_REFERER',
                                             reverse('produto:lista'))

        variacao_id = self.request.GET.get('vi')

        if not variacao_id:
            messages.error(self.request,
                           'produto não existe')

            return redirect(http_referer)
        variacao = get_object_or_404(models.Variacao, id=variacao_id)

        produto = variacao.produto
        variacao_estoque = variacao.estoque

        produto_id = variacao.id
        produto_nome = variacao.nome
        variacao_nome = variacao.nome or ''
        preco_unitario = variacao.preco
        preco_unitario_promocional = variacao.preco_promocional
        quantidade = 1
        slug = produto.slug
        imagem = produto.imagem

        if imagem:
            imagem = imagem.name
        else:
            imagem = ''

        if variacao.estoque < 1:
            messages.error(
                self.request,
                'Estoque insuficiente'
            )
            return redirect(http_referer)

        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()

        Carrinho = self.request.session['carrinho']

        if variacao_id in Carrinho:

            quantidade_carrinho = Carrinho[variacao_id]['quantidade']
            quantidade_carrinho += 1

            if variacao_estoque < quantidade_carrinho:
                messages.warning(
                    self.request,
                    f'Estoque insuficiente para {quantidade_carrinho}x no '
                    f'produto "{produto_nome}". Adicionamos {variacao_estoque}x '
                    f'no seu carrinho'
                )
                quantidade_carrinho = variacao_estoque
            Carrinho[variacao_id]['quantidade'] = quantidade_carrinho
            Carrinho[variacao_id]['preco_quantitativo'] = preco_unitario * \
                quantidade_carrinho
            Carrinho[variacao_id]['preco_quantitativo_promocional'] = preco_unitario_promocional * \
                quantidade_carrinho
        else:

            Carrinho[variacao_id] = {
                'produto_id': produto_id,
                'produto_nome': produto_nome,
                'variacao_nome': variacao_nome,
                ' variacao_id': variacao_id,
                'preco_unitario': preco_unitario,
                'preco_unitario_promocional': preco_unitario_promocional,
                'preco_quatitativo': preco_unitario,
                'preco_quatitativo_promocional': preco_unitario_promocional,
                'quantidade': 1,
                'slug': slug,
                'imagem': imagem
            }

        self.request.session.save()
        messages.success(self.request, f'Produto {produto_nome} {variacao_nome} adicionado ao seu '
                         f'carrinho {Carrinho[variacao_id]["quantidade"]}x.')
        return redirect(http_referer)


class RemoverDoCarrinho(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get('HTTP_REFERER',
                                             reverse('produto:lista'))

        variacao_id = self.request.GET.get('vid')

        if not variacao_id:

            return redirect(http_referer)

        if not self.request.session.get('carrinho'):
            return redirect(http_referer)

        if variacao_id not in self.request.session['carrinho']:
            return redirect(http_referer)

        carrinho = self.request.session['carrinho'][variacao_id]

        messages.success(
            self.request,
            f'Produto {carrinho["produto_nome"]}'
            f'removido do seu carrinho'
        )
        del self.request.session['carrinho'][variacao_id]
        self.request.session.save()
        variacao_id = self.request.GET.get('vid')
        return HttpResponse('RemoverDoCarrinho')


class Carrinho(View):
    def get(self, *args, **kwargs):

        return render(self.request, 'produto/carrinho.html')


class ResumoDaCompra(ListView):

    def get(self, *args, **kwargs):

        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')

        perfil = Perfil.objects.filter(usuario=self.request.user).exists()

        if not perfil:
            messages.error(
                self.request,
                'Usuario sem perfil.'
            )
            return redirect('perfil:criar')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Carrinho vazio'
            )
            return redirect('produto:lista')

        context = {
            'usuario': self.request.user,
            'carrinho': self.request.session['carrinho'],
        }

        return render(self.request, 'produto/resumodacompra.html', context)

produto/templates/produto/carrinho.html
{% extends 'base.html' %}
{% load omfilters %}

{% block conteudo%}
{% if request.session.carrinho %}
<main class="container mt-4 mb-4">

    {% include 'parciais/_carrinho.html' %}


    <div class="row mt-3">
        <div class="col-lg">
            <p class='lead'>Total no carrinho</p>

            <div class='table-responsive'>
                <table class="table">
                    <tr>
                        <td class="font-weight-bold">Total</td>

                        <td>{{ request.session.carrinho|cart_totais|formata_preco }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-lg mt-auto">
            {% if request.user.is_authenticated %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'produto:resumodacompra' %}">
                Comprar
            </a>
            {% else %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'perfil:criar' %}">
                Entrar e comprar
            </a>
            {% endif %}
        </div>
    </div>
    {% else %}

    <div class="row mt-3">
        <div class="col">
            <h3> Carrinho vazio </h3>
            <p class='lead'> Não há produtos no seu carrinho </p>
        </div>
    </div>

    {% endif%}

    {% endblock %}

produto/templates/produto/detalhe.html
{% extends 'base.html' %}
{% load omfilters %}
{% block conteudo %}
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg">
                <div class="row no-gutters">
                    <div class="col-lg-12">
                        {% if produto.imagem %}
                        <img class="img-fluid" src="{{ produto.imagem.url }}">
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-lg">
                <div class="mt-4 mt-lg-0">
                    <h1 class="h2">{{ produto.nome}}</h1>
                    <p class="lead"> {{ produto.curt_descrition }}</p>
                    <p class="lead">
                        {% if produto.cost_marketing_promotion %}
                        <span id="variation-preco-promocional" class="lead product-price">
                            {{ produto.cost_marketing_promotion | formata_preco}}
                        </span>
                        <span id="variation-preco" class="lead product-old-price text-muted">
                            {{ produto.cost_marketing | formata_preco}}
                        </span>
                        {% else%}
                        <span id="variation-preco" class="lead product-price">
                            {{ produto.cost_marketing | formata_preco}}
                        </span>
                        {% endif%}
                    </p>


                    <form action="{% url 'produto:adicionaraocarrinho' %}" id="form-add-to-cart">
                        <div class="form-group">
                            <select id="select-variacoes" name="vi" class="form-control form-control-lg">
                                {% for variacao in produto.variacao_set.all %}

                                {% if variacao.preco_promocional %}
                                <option data-preco="{{ variacao.preco | formata_preco}}"
                                    data-preco-promocional="{{ variacao.preco_promocional | formata_preco }}"
                                    value="{{ variacao.id }}">
                                    {% if variacao.nome %}
                                    {{ variacao.nome}}
                                    {% else%}
                                    {{variacao}}
                                    {% endif %}
                                </option>
                                {% else%}
                                <option data-preco="{{ variacao.preco | formata_preco}}" value="{{ variacao.id }}">
                                    {{% if variacao.nome %}
                                    {{ variacao.nome}}
                                    {% else%}
                                    {{variacao}}
                                    {% endif %}
                                </option>
                                {% endif %}

                                {% endfor%}
                            </select>
                        </div>

                        <div class="text-left">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Adicionar ao carrinho
                            </button>
                        </div>

                    </form>


                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-12">
                <div class="mt-5 mb-5">
                    <h2 class="text-center">{{produto.nome }}</h2>
                    {{ produto.long_descrition | linebreaks}}
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock%}

produto/templates/produto/lista.html
{% extends 'base.html' %}
{% load omfilters %}
{% block conteudo%}
<div class="row">
    <div class="col-lg-12">
        <div class="card-columns">

            {% for produto in produtos %}
            <div class="card">

                {% if produto.imagem %}
                <a href="{{produto.slug}}">
                    <img class="card-img-top" src=" {{ produto.imagem.url }}" alt="{{produto.nome}}">
                </a>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title"> {{produto.nome}}</h5>
                    <p class="card-text">{{ produto.curt_descrition}}</p>
                    <div class="container product-price-block text-center">
                        {% if produto.cost_marketing_promotion %}
                        <span class="product-price">
                            {{ produto.cost_marketing_promotion | formata_preco}}
                        </span>
                        <span class="product-old-price text-muted">
                            {{ produto.cost_marketing | formata_preco}}
                        </span>
                        {% else %}
                        <span class="product-price">
                            {{ produto.cost_marketing | formata_preco}}
                            {% endif %}
                    </div>
                </div>
                <div class="card-footer bg-transparent border-top-light-custom text-center">
                    <a href=" {{produto.slug}} " class="btn btn-primary btn-sm m-1 btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Comprar
                    </a>
                </div>
            </div>
            {% endfor %}




        </div>
    </div>
</div>
<div class="row mt-3">
    <div class="col">
        {% include 'parciais/_pagination.html'%}
    </div>
</div>
{% endblock %}

produto/templates/produto/resumodacompra.html
{% extends 'base.html' %}
{% load omfilters%}
{% block conteudo %}

<div class="row mt-3">
    <div class="col">
        <h3>resumo do carrinho</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>
        {% include 'parciais/_carrinho.html' %}




    </div>
</div>

<div class="col">

    <p class="lead text-center"><strong> Total do carrinho:</strong> {{ carrinho|cart_totais|formata_preco}}</p>
</div>
<div class="row">
    <div class="col">
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'pedido:pagar' %}">
            Realizar pedido e pagar
        </a>
    </div>
</div>
{% endblock%}